require("dotenv").config();
const request = require("supertest");
const { expect } = require("chai");

describe("/users/login endpoint API tests", () => {
  it("Should login with existing user - 200 success status code", async () => {
    const autoGeneratedUser = `auto_generated_user_${Date.now()}_1`;

    await request(process.env.API_HOST)
      .post("/users/register")
      .send({
        username: autoGeneratedUser,
        password: "123",
      })
      .set("Accept", "application/json");

    const response = await request(process.env.API_HOST)
      .post("/users/login")
      .send({
        username: autoGeneratedUser,
        password: "123",
      })
      .set("Accept", "application/json");

    
    expect(response.statusCode).to.equal(200);
    expect(response.text).to.contain("Login succeeded");
  });
});
