require("dotenv").config();
const request = require("supertest");
const { expect } = require("chai");

describe("/users/register endpoint API tests", () => {
  it("Should create new user - 200 success status code", async () => {
    const response = await request(process.env.API_HOST)
      .post("/users/register")
      .send({
        username: `auto_generated_user_${Date.now()}`,
        password: "123",
      })
      .set("Accept", "application/json");

    expect(response.statusCode).to.equal(200);
    expect(response.text).to.contain("User created successfully");
  });

  it("Should fail creating duplicated user - 409 duplicate entry status code", async () => {
    const autoGeneratedUser = `auto_generated_user_${Date.now()}`;

    await request(process.env.API_HOST)
      .post("/users/register")
      .send({
        username: autoGeneratedUser,
        password: "123",
      })
      .set("Accept", "application/json");

    const response = await request(process.env.API_HOST)
      .post("/users/register")
      .send({
        username: autoGeneratedUser,
        password: "123",
      })
      .set("Accept", "application/json");

      console.log(response);

    expect(response.statusCode).to.equal(409);
    expect(response.text).to.contain(`Username \\\"${autoGeneratedUser}\\\" already exists`);
  });
});
